description = "Provides support Tapestry injections in Spock specifications"

dependencies {
	implementation project(':commons')
	implementation project(':tapestry-ioc')
	implementation "org.spockframework:spock-core:${versions.spock}"
	
	testImplementation "jakarta.inject:jakarta.inject-api:2.0.1"
    testImplementation "org.junit.jupiter:junit-jupiter:${versions.junitJupiter}"
}

test {
	useJUnit()
}
